title: Sivaraj Sankar
logo: /assets/img/CirclePhoto.png
description: 
  - Aspiring ML Engineer                 
  - ㅤㅤㅤㅤㅤㅤㅤㅤSoftware Developer - Financial Domain
#show_downloads: true
#theme: Minima
theme: jekyll-theme-minimal
